export const instruments = [
    { value: "triangle", text: "Synth (Triangle)" },
    { value: "sine", text: "Synth (Sine)" },
    { value: "square", text: "Synth (Square)" },
    { value: "sawtooth", text: "Synth (Sawtooth)" },
    { value: "piano", text: "Piano" },
    { value: "bass-electric", text: "Bass Electric" },
    { value: "bassoon", text: "Bassoon" },
    { value: "cello", text: "Cello" },
    { value: "clarinet", text: "Clarinet" },
    { value: "contrabass", text: "Contrabass" },
    { value: "flute", text: "Flute" },
    { value: "french-horn", text: "French Horn" },
    { value: "guitar-acoustic", text: "Guitar Acoustic" },
    { value: "guitar-electric", text: "Guitar Electric" },
    { value: "guitar-nylon", text: "Guitar Nylon" },
    { value: "harmonium", text: "Harmonium" },
    { value: "harp", text: "Harp" },
    { value: "organ", text: "Organ" },
    { value: "saxophone", text: "Saxophone" },
    { value: "trombone", text: "Trombone" },
    { value: "trumpet", text: "Trumpet" },
    { value: "tuba", text: "Tuba" },
    { value: "violin", text: "Violin" },
    { value: "xylophone", text: "Xylophone" },
];
